# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  backup:

services:

  ca_siege:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-siege
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=1010
    ports:
      - "1010:1010"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/siege:/etc/hyperledger/fabric-ca-server
    container_name: ca_siege
    networks:
      - backup
  
  ca_spoke:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-spoke
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=1111
    ports:
      - "1111:1111"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/spoke:/etc/hyperledger/fabric-ca-server
    container_name: ca_spoke
    networks:
      - backup

 
 
  ca_orderer: 
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=1212
    ports:
      - "1212:1212"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - backup